services:
  arrse:
    build: .
    container_name: arrse
    restart: unless-stopped
    env_file: .env
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${TV_PATH:-./media/TV}:/data/TV
      - ${MOVIES_PATH:-./media/Movies}:/data/Movies
      - ${CONFIG_PATH:-./config}:/config
      - ${CACHE_PATH:-./cache}:/cache
    stop_grace_period: 30m
